Resources:
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: accountId
          AttributeType: S
        - AttributeName: goalId
          AttributeType: S
        - AttributeName: transactionId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: accountId
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: "UsersGoals"
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: goalId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - goalAmount
              - createDate
            ProjectionType: INCLUDE
      GlobalSecondaryIndexes:
        - IndexName: "AccountTransactions"
          KeySchema:
            - AttributeName: accountId
              KeyType: HASH
            - AttributeName: transactionId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - transactionAmount
              - transactionDate
            ProjectionType: INCLUDE
        - IndexName: "GoalTransactions"
          KeySchema:
            - AttributeName: goalId
              KeyType: HASH
            - AttributeName: transactionId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - transactionAmount
              - transactionDate
            ProjectionType: INCLUDE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST